[package]
name = "git_commit"
version = "0.1.0"
authors = ["erick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_deploy = {path = "/home/erick/rust/auto_deploy"}